server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 2019
  connection-timeout: 5000ms
  servlet:
    context-path: /
    
spring:
  application:
    name: spirngboot2-rabbitmq
  # 热启动插件
  devtools:
    restart:
      enabled: true
      #exclude: static/**,templates/**,public/**
      #设置重启的目录
      additional-paths: src/main/java
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
